### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by wannaphongcom** [mbr/latex#3] opened 2015-05-23 10:34 UTC
I using Python 3.4.3 64 bit on windows 8.1 64 bit.
```python
>>> from latex import build_pdf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\py34\lib\site-packages\latex\__init__.py", line 3, in <module>
    from .build import build_pdf
  File "C:\py34\lib\site-packages\latex\build.py", line 4, in <module>
    from future.utils import raise_from
ImportError: cannot import name 'raise_from'
```

**Comment by mbr** [comment] 2015-05-25 19:13
I can't reproduce it here, sorry.

```
Python 3.4.3 (default, Apr 21 2015, 22:42:30) 
[GCC 4.2.1 Compatible Debian Clang 3.2 (tags/RELEASE_32/final)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from latex import build_pdf
>>> 
```

Which version of future do you have installed? Are you using virtualenv?

```
$ pip freeze -l
data==0.3
decorator==3.4.2
funcsigs==0.4
future==0.14.3
latex==0.5.2
shutilwhich==1.1.0
six==1.9.0
tempdir==0.6
wheel==0.24.0
```

**Comment by wannaphongcom** [comment] 2015-05-26 14:37
I not using virtualenv.  Version of future is 0.9.0.

**Comment by mbr** [comment] 2015-05-26 15:43
Then I assume you need to upgrade future. Try ``pip install -UI future``.

**Comment by mbr** [comment] 2015-05-27 07:47
Closing this for now. If your issue still isn't fixed, please reopen.

**Closed by mbr** 2015-05-27 07:47 UTC
